version: '2'
services:
    rent-app:
        image: rent
        external_links:
            - rent-postgresql:postgresql
            - rent-elasticsearch:elasticsearch
        environment:
            - SPRING_PROFILES_ACTIVE=prod
            - SPRING_DATASOURCE_URL=jdbc:postgresql://postgresql:5432/rent
            - JHIPSTER_SLEEP=10 # gives time for the database to boot before the application
            - SPRING_DATA_ELASTICSEARCH_CLUSTER_NODES=elasticsearch:9300
        ports:
            - 8080:8080
    rent-postgresql:
        extends:
            file: postgresql.yml
            service: rent-postgresql
    rent-elasticsearch:
        extends:
            file: elasticsearch.yml
            service: rent-elasticsearch
